include("./lazywarehouse.jl")
include("./collisionchecker.jl")

# define global constants for organizing the route array
jobcount = 5
vehiclecount = 2

u = jobcount vehiclecount 

routecosts = Array(Int,u,u)
# generated by pathcost module

routedefinitions = Array(Any,u,u)
# generated by A*

nodecosts = Array(Int,x*y)
# generated from map
# 1 dim array nodecosts[1] = cost to traverse node1

routeplan = planroutes(routecosts,jobcount,vehiclecount)
routeplots = plotroutes(vehiclecount,routeplan,routedefinitions)
animatedroutes = animateroutes(routeplots,nodecosts)
resolvedroutes = resolvecollisions(animatedroutes)